
package com.openbravo.pos.printer.screen;

import javax.swing.*;
//import java.awt.image.BufferedImage;
import com.openbravo.pos.printer.*;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.printer.label.BasicLabel;
import com.openbravo.pos.printer.label.BasicLabelForScreen;

public class DeviceLabelPanel extends javax.swing.JPanel implements DeviceLabelPrinter {

    private String m_sName;
    private String sGapLabel;
    private JLabelContainer m_jLabelContainer;
    private BasicLabel m_labelcurrent;
    

    /** Creates new form JPrinterScreen2 */
    public DeviceLabelPanel() {
        initComponents();

        m_sName = AppLocal.getIntString("PrinterLabel.Screen");

        m_labelcurrent = null;

        m_jLabelContainer = new JLabelContainer();
        m_jScrollView.setViewportView(m_jLabelContainer);
    }

    public String getLabelPrinterName() {
        return m_sName;
    }

    public String getLabelPrinterDescription() {
        return null;
    }

    public JComponent getLabelPrinterComponent() {
        return this;
    }

    public void reset() {
        m_labelcurrent = null;
        m_jLabelContainer.removeAllLabels();
        m_jLabelContainer.repaint();
    }

    public void beginLabel(String sCodePage, String sWidth, String sHeight, String sGap) {
        sGapLabel = sGap;
        m_labelcurrent = new BasicLabelForScreen();
    }

    public void printBarcodeBox(String sTypeBarcode, String sLabelX, String sLabelY, String sHeight, String sRotation, String sCode) {
        m_labelcurrent.printBarCode(sTypeBarcode, "bottom", sCode);
    }

    public void drawLineBox(String sLabelX, String sLabelY, String sWidth, String sHeight) {
    }

    public void drawRectangleBox(String sLabelX, String sLabelY, String sWidth, String sHeight) {
    }

    public void printTextBox(String sCharset, String sFontPoint, String sLabelX, String sLabelY, String sRotation, String sText) {
        m_labelcurrent.beginLine(10);        
        m_labelcurrent.printText(1, sText);
        m_labelcurrent.endLine();        
    }

    public void endLabel() {
        m_jLabelContainer.addLabel(new JLabel(m_labelcurrent), sGapLabel);
        m_labelcurrent = null;
    }

//    public void openDrawer() {
//        // Una simulacion
//        Toolkit.getDefaultToolkit().beep();
//    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jScrollView = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(m_jScrollView, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane m_jScrollView;
    // End of variables declaration//GEN-END:variables
}
